title: Dorja Cug # your name (or website title) here
logo: "/images/profilna.png?raw=true" # your photo (or logo) here
description: >
  Hello! Born in Zagreb, Croatia I graduated from the School of Art, Design, Graphics and Clothing Zabok, majoring in media technician. I've got a bachelor's degree in AV media from the Baltic Film School, and am continuing my studies at TLÜ as a Master's degree student at Digital Learning Games.<br>
  I am the author of several short films, almost all of which were shortlisted at multiple film festivals, with some winning awards. I've also worked on mumerous other films, mainly as a production designer.<br><br>
  As a game designer I have written for several projects, and did basic 2D/3D art and environmental design. 
  E-mail: cugdorja@gmail.com<br>
  Phone number: +385955441270
  <br>
  Programs I use: Blender, PremierePro, DaVinci Resolve, Gimp, Krita, Aseprite.
  <br>
  <a href="images/CV_Cug_Dorja.pdf" download>CV</a><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
