title: Dorja Cug # your name (or website title) here
logo: "/images/pfp.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Dorja, I was born in 2002 and I come from Zagreb, Croatia. I graduated from the School of Art, Design, Graphics and Clothing Zabok, majoring in media technician. I am the author of several short films, most of which were shortlisted at multiple film festivals. <br> <br>
   Programs I use: Blender, PremierePro, DaVinci Resolve, After FX, Photoshop, Krita, Aseprite.
  <br><br>
  <a href="https://www.linkedin.com/in/dorja-cug-b87803216/">LinkedIn Profil</a><br>
  <a href="https://vimeo.com/user99122011">Vimeo Profil</a><br> 
  <a href="https://www.artstation.com/its_fenn">Artstation Profil</a><br> 
  <a href="images/cv_cug_dorja.pdf" download>CV</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
