title: Dorja Cug # your name (or website title) here
logo: "/images/profilna.png?raw=true" # your photo (or logo) here
description: I was born in 2002 and I come from Zagreb, Croatia. I graduated from the School of Art, Design, Graphics and Clothing Zabok, majoring in media technician. Currently I am studying AV media at Baltic Film School. I am the author of several short films, almost all of which were shortlisted at multiple film festivals.<br><br>
E-mail: cugdorja@gmail.com<br>
Phone number: +385955441270
  <br>
Programs I use: Blender, PremierePro, DaVinci Resolve, ScenaristKIT, Gimp, Photoshop, Krita, Aseprite.
  <br>
  <a href="images/CV_Cug_Dorja.pdf" download>CV</a><br>
  <a href="images/Hanjilec_letter_of_recommendation.pdf" download>1st Letter of recommendation</a><br>
  <a href="images/Bilankov_letter_of_recommendation.pdf" download>2nd Letter of recommendation</a><br>
  <a href="https://vimeo.com/user99122011">Vimeo Profile</a><br> 
  <a href="https://www.artstation.com/its_fenn">Artstation Profile</a><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
