title: Dorja Cug # your name (or website title) here
logo: "/images/pfp.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Zovem se Dorja, rođena sam 2002. i dolazim iz Zagreba. Završila sam Školu za umjetnost, dizajn, grafiku i odjeću Zabok. Autorica sam nekolicine filmova od kojih je jedan izabran u užoj selekciji 4 filmska festivala.
  <br><br>
  Programi koje koristim: Blender, Photoshop, PremierePro, After FX, Illustrator, Krita, Aseprite. 
  <br><br>
  <a href="https://www.linkedin.com/in/dorja-cug-b87803216/">Moj LinkedIn profil</a> 
  <a href="https://vimeo.com/user99122011/">Moj Vimeo profil</a> 
  <a href="https://www.artstation.com/its_fenn">Moj Artstation profil</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
