title: Dorja Cug # your name (or website title) here
logo: "/images/pfp.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ime mi je Dorja, rođena sam 2002. i dolazim iz Zagreba. Završila sam Školu za umjetnost, dizajn, grafiku i odjeću Zabok, smjer medijski tehničar. Autorica sam nekolicine filmova od kojih je jedan izabran u užoj selekciji 4 filmska festivala.<br>U slobodno vrijeme bavim se alpinizmom i speleologijom.
  <br>
  Programi koje koristim: Blender, Photoshop, PremierePro, After FX, Illustrator, Krita, Aseprite. 
  <br>
  <a href="https://www.linkedin.com/in/dorja-cug-b87803216/">LinkedIn profil</a><br>
  <a href="https://vimeo.com/user99122011/">Vimeo profil</a><br> 
  <a href="https://www.artstation.com/its_fenn">Artstation profil</a><br> 
 <a href="images/cv_cug-dorja.pdf" download>CV</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
